# Uncomment this line to define a global platform for your project
# platform :ios, '9.0'

target 'UU_Recommed_SDK' do
  # Uncomment this line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for UU_Recommed_SDK


       # Network
	pod 'AFNetworking'
	# Database 
	pod 'FMDB'
	pod 'TMCache'
    pod 'YYModel'
    pod 'MJExtension'

end
